"""your message

Revision ID: 76419232ede7
Revises: 
Create Date: 2024-04-15 00:51:06.088832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76419232ede7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
